# Generated by Django 5.2 on 2025-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('car_name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee per day', max_digits=8)),
                ('tracker_expiry_date', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('mileage', models.CharField(help_text='e.g. 29 mpg', max_length=20)),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Van', 'Van'), ('Convertible', 'Convertible'), ('Sport Car', 'Sport Car')], max_length=20)),
                ('gearbox', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('max_speed', models.CharField(max_length=20)),
                ('collision_damage_waiver', models.BooleanField(default=False)),
                ('third_party_liability_insurance', models.BooleanField(default=False)),
                ('optional_insurance_add_ons', models.BooleanField(default=False)),
                ('insurance_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Booked', 'Booked'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Active', max_length=10)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], default='Available', max_length=10)),
            ],
        ),
    ]
