# Generated by Django 5.2 on 2025-05-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_customer_delete_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('car_name', models.CharField(db_index=True, max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee per day', max_digits=8)),
                ('tracker_expiry_date', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('mileage', models.CharField(help_text='e.g. 29 mpg', max_length=20)),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Van', 'Van'), ('Convertible', 'Convertible'), ('Sport Car', 'Sport Car')], db_index=True, max_length=20)),
                ('gearbox', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10)),
                ('max_speed', models.CharField(max_length=20)),
                ('collision_damage_waiver', models.BooleanField(default=False)),
                ('third_party_liability_insurance', models.BooleanField(default=False)),
                ('optional_insurance_add_ons', models.BooleanField(default=False)),
                ('insurance_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Booked', 'Booked'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], db_index=True, default='Active', max_length=20)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Reserved', 'Reserved')], db_index=True, default='Available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['car_name'],
            },
        ),
        migrations.CreateModel(
            name='CarDeleteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Accident', 'Accident'), ('Maintenance', 'Maintenance'), ('Expired Insurance', 'Expired Insurance'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_reasons', to='cars.car')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'availability'], name='cars_car_status_2f94f9_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['type'], name='cars_car_type_3fba79_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['fee'], name='cars_car_fee_25c784_idx'),
        ),
    ]
