# Generated by Django 5.2 on 2025-05-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_cardeletereason_delete_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeletereason',
            name='reason',
            field=models.CharField(choices=[('Accident', 'Accident'), ('Maintenance', 'Maintenance'), ('Expired Insurance', 'Expired Insurance'), ('Others', 'Others')], max_length=100),
        ),
    ]
