# Generated by Django 5.2 on 2025-05-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_overdue_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='overdue_fee',
        ),
    ]
