# Generated by Django 5.2 on 2025-05-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
