# Generated by Django 5.2 on 2025-06-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtoken',
            name='device_type',
            field=models.CharField(default='mobile', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationtoken',
            name='platform',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtoken',
            unique_together={('token',)},
        ),
    ]
